### ISSUE TITLE
Can we merge video more than three 

### ISSUE THREAD

**Issue by Shahbaz-Akram** [mitsBhadeshiya/mergeVideos#2]

**Comment by mitsBhadeshiya** [comment]
@Shahbaz-Akram  yes we can merge N number of video in this code ... just you have to do dynamic code as per videos

**Comment by Shahbaz-Akram** [comment]
Can you share me code? or example?

**Comment by mitsBhadeshiya** [comment]
@Shahbaz-Akram  do your own that is not big deal just you have to understand the code and set as per videos
